### ISSUE TITLE
Inactive Host methods deadlock when Logger reenters Run

### ISSUE THREAD

**Issue by Burakuslendera** [Burakuslendera/mullion#159]
## Summary

An inactive public Host method can deterministically deadlock if its supported synchronous `Config.Logger` callback reenters `Host.Run`.

`Hide` is the minimal schedule. Before the first `Run`, or after a previous `Run` has returned, `Hide` admits itself and increments `runCalls` even though no Run is active. It then invokes `Logger.Debug` synchronously. If that callback calls `Run`, `beginRun` sees `running == false` and waits for `runCalls` to become zero. The outer `Hide` cannot execute its deferred `leaveRun` until the Logger and inner `Run` return.

Neither side can progress. No Runtime, COM callback, HWND, message pump, OS timing, or scheduler race is required.

## Expected behavior

A no-op public window-control call made while no Run is active must return. A Logger callback reached by that call must not be able to make the same goroutine wait on admission owned by the outer call.

The existing active-Run guarantees must remain intact: teardown waits for already-admitted public effects, a genuinely concurrent `Run` is rejected, and stale work cannot cross Run generations.

## Deterministic wait cycle

Starting with a newly constructed Host, or a Host whose previous Run has completed:

1. `Host.Hide` enters at `host/control_windows.go:46-50`.
2. `enterRun` takes a generation-zero snapshot with `running == false`, increments `host.runCalls`, and returns (`host/host_windows.go:408-427`).
3. `Hide` defers `leaveRun`, then calls `host.log.Debug("mullion: hide requested")`.
4. `logSink.Debug` invokes the caller's Logger synchronously (`host/logsink.go:34-37`).
5. That Logger calls `host.Run`.
6. `Run` enters `withRunGuard`, which calls `beginRun` (`host/host_windows.go:487-513`).
7. `beginRun` sees that no Run is active, then waits in `for host.runCalls != 0` (`host/host_windows.go:289-304`).
8. The only call that can decrement this count is the outer `Hide`'s deferred `leaveRun` at `host/host_windows.go:430-437`.
9. `Hide` cannot reach that defer until the Logger returns; the Logger cannot return until `Run` returns; `Run` cannot return until `Hide` decrements the count.

The same immediate-logging shape exists in `Show`, `Quit`, `Minimise`, `ToggleMaximise`, `StartDrag`, and `StartResize`. `Hide` alone is sufficient to prove the defect.

An active Run is not this schedule: when `running == true`, `beginRun` returns `host is already running` before the `runCalls` wait. The defect is specifically generation-zero admission while no Run is active.

## Contract contradiction

`docs/architecture.md:169-175` documents the lifecycle contract:

- an API call belongs to the Run active when it enters;
- entry uses a short counted admission and releases the mutex before native, caller, or Logger code;
- Logger-reentrant calls therefore cannot self-deadlock;
- teardown waits for admitted work before allowing the next Run.

The implementation satisfies the active-Run Logger-to-other-method case, but the unconditional generation-zero count makes Logger-to-`Run` reentry self-deadlock before a Run begins.

`host/doc.go:37-42` also promises that every Host method other than `Run` is safe from any goroutine and synchronizes its effects with Run teardown. The public comments for `Hide` and its sibling controls explicitly say that an inactive call has no window effect; they do not warn that it may block a future/reentrant Run forever.

## First bad commit and affected releases

`git blame` and the introducing diff identify `df1358088045ce12acef40b84241230ad127ddab` (`P0: close post-merge recurrence guards`, PR #119) as the first bad commit:

- it added `enterRun`/`leaveRun` around `Hide` and the sibling public controls;
- it added the generation-zero `runCalls` drain in `beginRun`;
- it added the active-Run Logger-reentry test, but not inactive Logger-to-Run reentry.

`df135808` is an ancestor of `v0.0.3` and current `main` (`43a719f3e6ae010a15fe453d3d494e7cc92240b5`), but not `v0.0.2`. Tags `v0.0.1` and `v0.0.2` had neither the counted public admission nor this wait cycle.

Affected: `v0.0.3` and current `main` on supported Windows 10/amd64 and Windows 11/amd64. The deadlock is pure Go synchronization and is independent of the installed WebView2 Runtime.

## Existing test and exact gap

`host/lifecycle_generation_windows_test.go:33-97`,
`TestLoggerMayReenterHostMethodWhileTeardownWaits`, proves a different and important schedule:

- a Run is active;
- outer `Hide` is admitted;
- `endRun` waits;
- the Logger reenters `Quit`;
- both public calls finish and teardown then completes.

That test never calls `Run` from the Logger and never starts in generation zero. It therefore cannot reach `beginRun`'s `runCalls` wait.

## Safe headless reproduction

No test should create a window.

Use a one-shot Logger whose `Debug` callback calls public `Host.Run`. Configure the Host with an existing deterministic source preflight error, such as a non-loopback `Config.URL`, so a repaired inner `Run` must return before runtime discovery, COM, class registration, or HWND creation.

Run two bounded cases:

1. call `Hide` before the first `Run`;
2. establish and finish one headless lifecycle generation, then call `Hide` and reenter `Run` again.

For each, require both the inner `Run` result and the outer `Hide` completion within the bound. A matched Logger that returns normally is the control. A subprocess form may be used to give a failed deadlock probe an unambiguous outer timeout and clean process termination.

Also retain the active-Run control: Logger reentry into `Run` while a Run is active must return the documented concurrent-Run error immediately, rather than waiting or starting another session.

## Acceptance criteria

- An inactive public method cannot make a synchronous Logger callback wait on admission owned by that same outer method.
- Before-first-Run and after-completed-Run Logger-to-`Run` reentry complete deterministically without Runtime, COM, HWND, or message-pump work.
- A truly concurrent `Run` on an active Host still returns `host is already running` immediately.
- `endRun` still waits for already-admitted active-Run methods and callbacks before poisoning the Run token.
- The existing active `Hide` to Logger `Quit` teardown schedule continues to complete and preserve both command effects.
- Sequential reuse, process-global token/HWND identity, stale-generation rejection, and callback admission closure remain unchanged.
- Headless regression tests cover the positive and negative schedules with bounded failure reporting.
- Canonical lifecycle/verification documentation records the generation-zero versus active-Run distinction and the test's proof boundary.

## Evidence boundary and nonclaims

- **Confirmed by source/history:** the exact synchronization cycle, first bad commit, released-tag range, and mismatch with the documented Logger-reentry invariant.
- **Not executed in this audit:** a dedicated deadlock subprocess or patched regression test.
- **No live verification required for classification:** the cycle occurs before all platform and Runtime work and has no timing-dependent edge.
- **Not claimed:** a data race, COM lifetime fault, cross-process influence, security boundary breach, HWND failure, WebView2 Runtime bug, or Windows 10/11 behavioral difference.
- This is a hang/deadlock, not an operation that returns success while doing nothing; the `silent-failure` label does not apply.
- The environment is not needed to investigate this deterministic synchronization cycle; `needs-repro` does not apply.

## Priority rationale

`P0: blocker`. The priority ladder explicitly classifies a deterministic deadlock/hang as P0. A public no-op control plus a supported Logger callback can prevent both the control and the next `Run` from ever returning.

## Duplicate review

- #140 owns `startupMu` being held across startup timing `Logger.Info`, followed by Logger reentry into `Show`. This issue uses neither `startupMu` nor active startup: it is generation-zero `runCalls` admission followed by Logger reentry into `Run`.
- #97 and merged PRs #118/#119 own teardown completeness, Run generation identity, stale HWND/private-command rejection, and active-Run Logger reentry. Their repair introduced this distinct generation-zero cycle.
- #141 owns external delivery of a predictable private Run token/window command, not in-process admission.
- #146 owns cross-Host panic diagnostic attribution, not liveness.
- #23 owns reentry while WebView2 Embed pumps messages, after startup has begun.
- #129 owns cross-OS lifecycle evidence and does not implement or own this defect.

Live exact-title, `runCalls`/`beginRun`/Logger, inactive-Host, and Hide/Run/deadlock searches found no other issue. No open pull request owns the root cause.

## Scheduling boundary

Open P0 blockers remain. This audit issue records a newly confirmed P0 under the maintainer's explicit issue-publication authorization. It authorizes no implementation, test execution, commit, push, merge, or unrelated scheduling.

**Comment by Burakuslendera** [comment]
Closing with a technical summary of the root cause and fix.

**Root cause:** public methods other than `Run` (`Hide`, `Show`, `Quit`, …) admitted themselves through a counted entry (`enterRun` → `runCalls++`) unconditionally. While no Run was active, a synchronous Logger call from an inactive method could re-enter `Run`; `beginRun` then waited for `runCalls == 0`, and the only side able to decrement was the outer call's deferred `leaveRun` — unreachable while the Logger, and therefore the inner `Run`, was still inside the outer call. Deterministic self-deadlock; a pure Go synchronization cycle (no Runtime, COM, HWND or scheduler timing involved). The shape was introduced by df13580 (PR #119) and affected v0.0.3 and main.

**Fix (PR #162, squash c4cdf37):** only an entry made while a Run is active joins the counted admission set:
- `runAdmission` gained a `counted` field; `enterRun` increments `runCalls` only when a Run is active;
- an inactive entry is admitted uncounted — it waits on nothing and nothing waits on it; `beginRun` no longer drains generation-zero work;
- `leaveRun(admission)` is a no-op for uncounted entries; `enterOriginatingRun` returns `(runAdmission, bool)` so a callback's count stays paired with the admission it was admitted into.

**Guarantees preserved:** concurrent-`Run` rejection ("host is already running"), the `endRun` teardown drain, stale-generation token/HWND rejection of tagged commands, and teardown-drain Logger re-entry (`TestLoggerMayReenterHostMethodWhileTeardownWaits`) — all unmodified.

**Tests:** new headless `host/inactive_run_admission_windows_test.go` — `TestInactiveHideSurvivesLoggerReentrantRunBeforeFirstRun`, `TestInactiveHideSurvivesLoggerReentrantRunAfterCompletedRun`, plain-Logger control `TestInactiveHideKeepsSequentialRunReachableWithPlainLogger`, active-Run rejection control `TestActiveRunLoggerReentrantRunIsRejectedAsConcurrent`. Both re-entry schedules fail bounded at 2 s on the unfixed tree; all four pass on the fixed one.

**Evidence:** gofmt / go vet / go build and the full `go test ./...` plus leak-scan pass locally; PR CI 5/5 SUCCESS. Known limitation: `-race` was not run locally (no GCC toolchain) and the CI checks do not cover the race detector.

**References:** decision `docs/decisions/0049-inactive-calls-are-admitted-uncounted.md`. Related: #140 / decision 0046 — same area (Logger re-entry), different mechanism (mutex-held emit vs. counted-admission drain).
